# Generated by Django 4.0.6 on 2022-07-21 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homesite', '0002_alter_ayyaam_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ayyaam',
            name='date',
        ),
    ]
