# Generated by Django 4.0.6 on 2022-07-21 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homesite', '0004_ayyaam_mydate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ayyaam',
            options={'verbose_name_plural': 'Date_Info'},
        ),
    ]
