# Generated by Django 4.0.6 on 2022-07-21 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homesite', '0005_alter_ayyaam_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ayyaam',
            options={'verbose_name_plural': 'Title_Info'},
        ),
    ]
