# Generated by Django 4.0.6 on 2022-07-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesite', '0006_alter_ayyaam_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='suggestons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField()),
                ('text', models.CharField(max_length=1200)),
            ],
            options={
                'verbose_name_plural': 'Suggestions',
            },
        ),
    ]
