# Generated by Django 4.0.6 on 2022-07-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesite', '0008_islamic_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscriptions',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('added_date', models.DateTimeField()),
                ('text', models.EmailField(max_length=1200)),
            ],
            options={
                'verbose_name_plural': 'Subscriptions',
            },
        ),
    ]
