# Generated by Django 4.0.6 on 2022-10-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesite', '0009_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='islamic_date',
            name='saal',
            field=models.IntegerField(default=0),
        ),
    ]
