# Generated by Django 4.1.3 on 2022-12-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesite', '0010_islamic_date_saal'),
    ]

    operations = [
        migrations.CreateModel(
            name='dateStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.IntegerField(default=0)),
                ('startMonth', models.IntegerField(default=0)),
                ('startYear', models.IntegerField(default=0)),
                ('IslamicDate', models.IntegerField(default=0)),
                ('IslamicMonth', models.IntegerField(default=0)),
                ('IslamicYear', models.IntegerField(default=0)),
            ],
        ),
    ]
