# Generated by Django 4.1.3 on 2022-12-03 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homesite', '0011_datestore'),
    ]

    operations = [
        migrations.DeleteModel(
            name='islamic_date',
        ),
        migrations.RemoveField(
            model_name='datestore',
            name='IslamicDate',
        ),
    ]
