# Generated by Django 4.1.3 on 2022-12-03 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homesite', '0012_delete_islamic_date_remove_datestore_islamicdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datestore',
            options={'verbose_name_plural': 'IslamicMonth'},
        ),
    ]
